# Header
menu:
  home: /
  archives: /archives
  about: /about.html
#rss: /atom.xml

banner: CODE THE WEB

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
#- tagcloud
- archive
#- recent_posts
- links

# Links
links:
  阮一峰: http://www.ruanyifeng.com/blog/
  左耳朵耗子: http://coolshell.cn/
  阿里郎小胡子哥: http://www.barretlee.com/entry/
  大漠弟子pinggod: http://pinggod.com/
  Jamling(参考样式): http://ieclipse.cn/
  屠城(参考字体): https://www.haomwei.com/

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo, 推荐放在站点配置文件中
duoshuo_shortname: 

# Baidu share
baidushare: true

#swiftype 搜索, 推荐放在站点配置文件中
swiftype_key: 

#百度统计, 推荐放在站点配置文件中
baidu_analytics:  
